import { AppHeader } from '@/components/layout/AppHeader';
import { AppText } from '@/components/ui/AppText';
import { Card } from '@/components/ui/Card';
import { Screen } from '@/components/ui/Screen';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/States';
import { useProperty } from '@/contexts/PropertyContext';
import { useAppTheme } from '@/contexts/ThemeContext';
import { useAsyncData } from '@/hooks/useAsyncData';
import { auditRepository } from '@/repositories/api-repositories';
import { palette, radius, spacing } from '@/theme/tokens';
import { AuditLog } from '@/types';
import { formatDate } from '@/utils/format';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
export default function AuditScreen() { const { activeProperty } = useProperty(); const { colors } = useAppTheme(); const [query, setQuery] = useState(''); const [expanded, setExpanded] = useState<string | null>(null); const state = useAsyncData(() => auditRepository.list(activeProperty?.id), [activeProperty?.id]); const rows = useMemo(() => (state.data?.data ?? []).filter((item) => `${item.userName} ${item.action} ${item.module} ${item.summary}`.toLowerCase().includes(query.toLowerCase())), [query, state.data]); return <Screen header={<AppHeader title="Istoric modificări" back onBack={() => router.replace('/service/more')} />} refreshing={state.refreshing} onRefresh={() => void state.reload(true)}><View><AppText variant="title">Jurnal complet de audit</AppText><AppText muted>Acțiuni înregistrate de API, asociate utilizatorului și proprietății.</AppText></View><Card style={[styles.search, { backgroundColor: colors.input }]}><Ionicons name="search-outline" size={19} color={colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder="Caută utilizator, acțiune sau modul…" placeholderTextColor={colors.textMuted} style={{ flex: 1, color: colors.text }} /></Card>{state.loading ? <LoadingState rows={6} /> : state.error ? <ErrorState message={state.error.message} /> : !rows.length ? <EmptyState icon="time-outline" title="Nicio acțiune găsită" message="Istoricul va apărea aici după utilizarea aplicației." /> : <View style={styles.list}>{rows.map((item) => <AuditCard key={item.id} item={item} expanded={expanded === item.id} onPress={() => setExpanded((current) => current === item.id ? null : item.id)} />)}</View>}</Screen>; }
function AuditCard({ item, expanded, onPress }: { item: AuditLog; expanded: boolean; onPress: () => void }) { const { colors } = useAppTheme(); return <Pressable onPress={onPress}><Card style={styles.audit}><View style={[styles.icon, { backgroundColor: colors.primarySoft }]}><Ionicons name={item.action.includes('DELETE') ? 'trash-outline' : item.action.includes('LOGIN') ? 'log-in-outline' : 'create-outline'} size={20} color={item.action.includes('DELETE') ? palette.danger : colors.primary} /></View><View style={{ flex: 1, gap: 3 }}><View style={styles.row}><AppText variant="label" style={{ flex: 1 }}>{item.summary}</AppText><AppText variant="caption" muted>{formatDate(item.createdAt, true)}</AppText></View><AppText variant="caption" muted>{item.userName || 'Sistem'} · {item.module} · {item.action}</AppText>{expanded ? <View style={[styles.details, { backgroundColor: colors.surfaceMuted }]}><AppText variant="caption">Entitate: {item.entityType || '—'} · ID: {item.entityId || '—'}</AppText><AppText variant="caption">IP: {item.ipAddress || '—'} · Dispozitiv: {item.device || '—'}</AppText>{item.before ? <AppText variant="caption" muted>Înainte: {JSON.stringify(item.before)}</AppText> : null}{item.after ? <AppText variant="caption" muted>După: {JSON.stringify(item.after)}</AppText> : null}</View> : null}</View><Ionicons name={expanded ? 'chevron-up' : 'chevron-down'} size={18} color={colors.textMuted} /></Card></Pressable>; }
const styles = StyleSheet.create({ search: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.sm }, list: { gap: spacing.md }, audit: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, icon: { width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, flexWrap: 'wrap' }, details: { marginTop: spacing.md, padding: spacing.md, borderRadius: radius.sm, gap: spacing.sm } });
