import { AppHeader } from '@/components/layout/AppHeader';
import { QRChart } from '@/components/dashboard/QRChart';
import { StatCard } from '@/components/dashboard/StatCard';
import { AppText } from '@/components/ui/AppText';
import { Card } from '@/components/ui/Card';
import { Screen } from '@/components/ui/Screen';
import { ErrorState, LoadingState } from '@/components/ui/States';
import { useProperty } from '@/contexts/PropertyContext';
import { useAppTheme } from '@/contexts/ThemeContext';
import { useAsyncData } from '@/hooks/useAsyncData';
import { apiRequest } from '@/services/api';
import { palette, radius, spacing } from '@/theme/tokens';
import { Commission, DashboardMetrics } from '@/types';
import { formatCurrency } from '@/utils/format';
import { StyleSheet, View } from 'react-native';
type Report = { metrics: DashboardMetrics; commissions: Commission[]; revenueByMonth: { label: string; value: number }[]; totalCosts: number; netProfit: number };
export default function ReportsScreen() { const { activeProperty } = useProperty(); const { colors } = useAppTheme(); const state = useAsyncData(() => apiRequest<Report>(`/reports?propertyId=${activeProperty?.id}`), [activeProperty?.id]); if (state.loading) return <Screen header={<AppHeader title="Rapoarte" back />}><LoadingState rows={6} /></Screen>; if (state.error || !state.data) return <Screen header={<AppHeader title="Rapoarte" back />}><ErrorState message={state.error?.message ?? 'Rapoarte indisponibile.'} /></Screen>; const report = state.data; const max = Math.max(1, ...report.revenueByMonth.map((item) => item.value)); return <Screen header={<AppHeader title="Rapoarte" back />} refreshing={state.refreshing} onRefresh={() => void state.reload(true)}><View><AppText variant="title">Performanța proprietății</AppText><AppText muted>Indicatori calculați exclusiv din baza online.</AppText></View><View style={styles.stats}><StatCard label="Venit estimat" value={formatCurrency(report.metrics.estimatedRevenue)} icon="trending-up-outline" color={palette.success} /><StatCard label="Costuri directe" value={formatCurrency(report.totalCosts)} icon="trending-down-outline" color={palette.danger} /><StatCard label="Profit net" value={formatCurrency(report.netProfit)} icon="wallet-outline" color={palette.electric} /><StatCard label="Comisioane" value={formatCurrency(report.metrics.collaboratorCommissions)} icon="people-outline" color={palette.purple} /></View><View style={styles.columns}><Card style={styles.panel}><AppText variant="heading">Activitate QR</AppText><QRChart generated={report.metrics.qrGenerated} used={report.metrics.qrUsed} /></Card><Card style={styles.panel}><AppText variant="heading">Venituri pe luni</AppText><View style={styles.bars}>{report.revenueByMonth.map((item) => <View key={item.label} style={styles.barColumn}><View style={styles.barValue}><AppText variant="caption" muted>{formatCurrency(item.value)}</AppText></View><View style={[styles.barTrack, { backgroundColor: colors.surfaceMuted }]}><View style={[styles.bar, { height: `${Math.max(8, (item.value / max) * 100)}%`, backgroundColor: colors.primary }]} /></View><AppText variant="caption" muted>{item.label}</AppText></View>)}</View></Card></View><Card style={styles.panel}><AppText variant="heading">Comisioane colaboratori</AppText>{report.commissions.length ? report.commissions.slice(0, 10).map((item) => <View key={item.id} style={[styles.commission, { borderBottomColor: colors.border }]}><AppText variant="label" style={{ flex: 1 }}>Fișă {item.serviceSheetId?.slice(0, 8) ?? 'fără număr'}</AppText><AppText variant="caption" muted>{item.type === 'PERCENT_NET' ? `${item.rateOrAmount}% din net` : 'Sumă fixă'}</AppText><AppText variant="label" style={{ color: palette.success }}>{formatCurrency(item.commissionValue)}</AppText></View>) : <AppText muted>Nu există comisioane calculate.</AppText>}</Card></Screen>; }
const styles = StyleSheet.create({ stats: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, columns: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, panel: { flex: 1, minWidth: 290, gap: spacing.lg }, bars: { height: 230, flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm }, barColumn: { flex: 1, height: '100%', alignItems: 'center', gap: 4 }, barValue: { height: 38, justifyContent: 'flex-end' }, barTrack: { flex: 1, width: '70%', borderRadius: radius.sm, overflow: 'hidden', justifyContent: 'flex-end' }, bar: { width: '100%', borderRadius: radius.sm }, commission: { flexDirection: 'row', gap: spacing.md, paddingVertical: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth } });
