import { AppText } from '@/components/ui/AppText';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { useAuth } from '@/contexts/AuthContext';
import { useAppTheme } from '@/contexts/ThemeContext';
import { useToast } from '@/contexts/ToastContext';
import { clientRepository } from '@/repositories/api-repositories';
import { palette, radius, spacing } from '@/theme/tokens';
import { Client } from '@/types';
import { formatDate } from '@/utils/format';
import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import * as MediaLibrary from 'expo-media-library';
import { router } from 'expo-router';
import { useRef, useState } from 'react';
import { Linking, Modal, Platform, Pressable, Share, StyleSheet, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { captureRef } from 'react-native-view-shot';

const messageFor = (link: string) => `Bună ziua, pentru înregistrarea solicitării dumneavoastră, vă rugăm să accesați linkul următor și să completați datele necesare service-ului: ${link}`;
export function ClientQRPanel({ client }: { client: Client }) {
  const { colors } = useAppTheme(); const { hasPermission } = useAuth(); const { showToast } = useToast(); const qrRef = useRef<View>(null); const [shareOpen, setShareOpen] = useState(false); const qr = client.qr; const link = qr?.publicUrl ?? '';
  const record = async (method: string) => { try { await clientRepository.recordQrShare(client.id, method); } catch { /* Share action is still useful if analytics fail. */ } };
  const shareNative = async () => { if (!link) return; const result = await Share.share({ title: 'Cod QR G-Shop', message: messageFor(link), url: link }); if (result.action === Share.sharedAction) { await record('NATIVE'); showToast('Linkul QR a fost partajat.', 'success'); } };
  const openExternal = async (method: 'WHATSAPP' | 'EMAIL' | 'SMS') => { if (!link) return; const message = encodeURIComponent(messageFor(link)); const url = method === 'WHATSAPP' ? `https://wa.me/?text=${message}` : method === 'EMAIL' ? `mailto:${client.email ?? ''}?subject=${encodeURIComponent('Formular service G-Shop')}&body=${message}` : `sms:${client.phone}${Platform.OS === 'ios' ? '&' : '?'}body=${message}`; const supported = await Linking.canOpenURL(url); if (!supported) return showToast('Metoda nu este disponibilă pe acest dispozitiv.', 'error'); await Linking.openURL(url); await record(method); setShareOpen(false); };
  const copy = async () => { await Clipboard.setStringAsync(link); await record('COPY'); setShareOpen(false); showToast('Linkul a fost copiat.', 'success'); };
  const save = async () => { if (!qrRef.current) return; const permission = await MediaLibrary.requestPermissionsAsync(); if (!permission.granted) return showToast('Permite accesul la galerie pentru a salva QR-ul.', 'error'); try { const uri = await captureRef(qrRef, { format: 'png', quality: 1 }); await MediaLibrary.saveToLibraryAsync(uri); showToast('Codul QR a fost salvat în galerie.', 'success'); } catch { showToast('Imaginea QR nu a putut fi salvată.', 'error'); } };
  if (!qr || qr.status === 'NOT_GENERATED') return <Card style={styles.empty}><View style={[styles.bigIcon, { backgroundColor: colors.surfaceMuted }]}><Ionicons name="qr-code-outline" size={42} color={colors.textMuted} /></View><AppText variant="heading">Cod QR indisponibil</AppText><AppText muted style={styles.center}>Această înregistrare provine din versiunea anterioară. Clienții noi primesc automat codul QR la adăugare.</AppText></Card>;
  if (!hasPermission('qr.share')) return <Card style={styles.empty}><View style={[styles.bigIcon, { backgroundColor: colors.surfaceMuted }]}><Ionicons name="lock-closed-outline" size={40} color={colors.textMuted} /></View><AppText variant="heading">Cod QR protejat</AppText><AppText muted style={styles.center}>Contul tău poate vedea clientul, dar afișarea, salvarea și trimiterea codului necesită permisiunea „Trimite QR”.</AppText>{hasPermission('qr.scan') ? <Button label="Scanează un cod QR" icon="scan-outline" variant="secondary" onPress={() => router.push('/service/qr-scanner')} /> : null}</Card>;
  const qrValue = link || qr.token;
  if (!qrValue) return <Card style={styles.empty}><View style={[styles.bigIcon, { backgroundColor: colors.surfaceMuted }]}><Ionicons name="cloud-offline-outline" size={40} color={colors.textMuted} /></View><AppText variant="heading">Date QR indisponibile</AppText><AppText muted style={styles.center}>Datele securizate ale codului nu au putut fi încărcate. Reîncarcă pagina și încearcă din nou.</AppText></Card>;
  const displayStatus = qr.status === 'REGENERATED' ? 'GENERATED' : qr.status;
  return <>
    <Card style={styles.panel}><View style={styles.top}><View><AppText variant="heading">Cod QR client</AppText><AppText variant="caption" muted>Generat {formatDate(qr.generatedAt, true)}</AppText></View><StatusBadge status={displayStatus} /></View><View ref={qrRef} collapsable={false} style={styles.qrBox}><QRCode value={qrValue} size={220} color="#07152D" backgroundColor="#FFFFFF" logo={require('@/logo/logo.png')} logoSize={38} logoBorderRadius={9} /></View><AppText variant="caption" muted style={styles.center}>Token securizat · fără date personale în cod</AppText><View style={styles.buttons}><Button label="Trimite codul QR" icon="send-outline" onPress={() => setShareOpen(true)} style={{ flex: 1 }} /><Button label="Salvează" icon="download-outline" variant="outline" onPress={() => void save()} /></View><View style={styles.buttons}><Button label="Scanează" compact icon="scan-outline" variant="secondary" onPress={() => router.push('/service/qr-scanner')} style={{ flex: 1 }} /><Button label="Simulează formularul" compact icon="create-outline" variant="secondary" onPress={() => qr.token && router.push(`/public/client-form/${qr.token}`)} style={{ flex: 1 }} /></View></Card>
    <Modal transparent visible={shareOpen} animationType="slide" onRequestClose={() => setShareOpen(false)}><Pressable style={[styles.overlay, { backgroundColor: colors.overlay }]} onPress={() => setShareOpen(false)}><Pressable style={[styles.sheet, { backgroundColor: colors.surface }]} onPress={(event) => event.stopPropagation()}><View style={styles.handle} /><AppText variant="title">Trimite codul QR</AppText><AppText muted>Alege metoda potrivită pentru client.</AppText><View style={styles.shareGrid}><ShareOption icon="logo-whatsapp" label="WhatsApp" color="#19A957" onPress={() => void openExternal('WHATSAPP')} /><ShareOption icon="mail-outline" label="Email" color={palette.electric} onPress={() => void openExternal('EMAIL')} /><ShareOption icon="chatbox-outline" label="SMS" color={palette.purple} onPress={() => void openExternal('SMS')} /><ShareOption icon="copy-outline" label="Copiază link" color={palette.warning} onPress={() => void copy()} /></View><Button label="Partajare nativă" icon="share-social-outline" onPress={() => void shareNative()} /><Button label="Închide" variant="ghost" onPress={() => setShareOpen(false)} /></Pressable></Pressable></Modal>
  </>;
}
function ShareOption({ icon, label, color, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; color: string; onPress: () => void }) { const { colors } = useAppTheme(); return <Pressable onPress={onPress} style={[styles.option, { borderColor: colors.border }]}><View style={[styles.optionIcon, { backgroundColor: `${color}18` }]}><Ionicons name={icon} size={24} color={color} /></View><AppText variant="label">{label}</AppText></Pressable>; }
const styles = StyleSheet.create({ empty: { alignItems: 'center', gap: spacing.md, paddingVertical: spacing.xxxl }, bigIcon: { width: 78, height: 78, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, center: { textAlign: 'center' }, panel: { gap: spacing.lg }, top: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md, alignItems: 'center' }, qrBox: { padding: spacing.lg, backgroundColor: '#fff', borderRadius: radius.lg, alignSelf: 'center' }, buttons: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, overlay: { flex: 1, justifyContent: 'flex-end' }, sheet: { width: '100%', maxWidth: 620, alignSelf: 'center', borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xxl, gap: spacing.md }, handle: { width: 42, height: 5, borderRadius: 3, backgroundColor: '#AAB5C5', alignSelf: 'center', marginBottom: spacing.sm }, shareGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginVertical: spacing.md }, option: { minWidth: 120, flex: 1, borderWidth: 1, borderRadius: radius.lg, padding: spacing.md, alignItems: 'center', gap: spacing.sm }, optionIcon: { width: 48, height: 48, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' } });
