<?php
$token = preg_replace('/[^a-fA-F0-9-]/', '', (string)($_GET['token'] ?? ''));
?><!doctype html>
<html lang="ro">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#ffffff">
  <meta name="robots" content="noindex,nofollow,noarchive">
  <link rel="icon" type="image/png" sizes="512x512" href="./assets/logo.png">
  <link rel="apple-touch-icon" href="./assets/logo.png">
  <title>Status reparație · G-Shop</title>
  <style>
    :root{color-scheme:only light;--blue:#0879db;--blue-deep:#0754b7;--blue-soft:#eaf5ff;--ink:#111827;--muted:#718096;--line:#e5eaf1;--canvas:#f1f6fb;--white:#fff;--green:#17ad54;--green-soft:#eaf9ef;--orange:#f09a00;--orange-soft:#fff5e3;--red:#e43b50;--red-soft:#fff0f2;--purple:#7651ad;--purple-soft:#f4effc;--teal:#0c93b6;--status:#0879db;--status-soft:#eaf5ff;--shadow:0 14px 38px rgba(25,48,80,.08)}
    *{box-sizing:border-box}
    html{background:var(--canvas);overflow-x:hidden}
    body{margin:0;min-height:100vh;overflow-x:hidden;background:radial-gradient(circle at 50% -100px,#e6f2ff 0,transparent 360px),var(--canvas);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
    button,a{font:inherit;-webkit-tap-highlight-color:transparent}
    button{border:0}
    .page{width:100%;max-width:480px;min-height:100vh;margin:0 auto;padding:calc(12px + env(safe-area-inset-top)) 12px calc(92px + env(safe-area-inset-bottom))}
    .header{text-align:center;padding:4px 10px 15px}
    .brand{display:flex;align-items:center;justify-content:center;gap:8px}.brand-logo{width:47px;height:47px;object-fit:contain;filter:drop-shadow(0 7px 10px rgba(7,92,255,.18))}.brand-copy{text-align:left}.brand-title{font-size:16px;line-height:1;font-weight:950;letter-spacing:-.3px}.brand-property{display:block;max-width:220px;margin-top:4px;color:var(--muted);font-size:9px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .tracking-title{font-size:17px;line-height:1.25;margin:12px 0 6px;font-weight:900;letter-spacing:-.3px}.live{display:flex;align-items:center;justify-content:center;gap:7px;color:#526176;font-size:10px;font-weight:650}.live-dot{width:7px;height:7px;border-radius:50%;background:#20bd5b;box-shadow:0 0 0 0 rgba(32,189,91,.35);animation:live-pulse 1.8s infinite}
    .card{background:var(--white);border:1px solid var(--line);border-radius:15px;box-shadow:var(--shadow)}
    .sheet-card{padding:15px;margin-bottom:12px;animation:rise .42s ease both}.sheet-label{color:#5d6c81;font-size:10px;font-weight:700}.sheet-number{display:block;margin-top:2px;font-size:15px;font-weight:950;letter-spacing:.15px}.equipment{margin:15px 0 13px;font-size:14px;font-weight:850;line-height:1.35}.sheet-meta{display:grid;grid-template-columns:1fr 1fr}.meta{min-width:0}.meta+.meta{border-left:1px solid var(--line);padding-left:14px}.meta-label{display:block;color:#9a7d75;font-size:9px;font-weight:650;margin-bottom:4px}.meta-value{display:block;font-size:11px;font-weight:850;line-height:1.35;overflow-wrap:anywhere}
    .document-link{min-height:54px;margin:-3px 0 12px;padding:8px 10px;border:1px solid #cfe1f6;border-radius:14px;background:linear-gradient(135deg,#f7fbff,#eaf5ff);color:var(--blue-deep);text-decoration:none;display:flex;align-items:center;gap:10px;font-size:12px;font-weight:900;box-shadow:0 9px 25px rgba(8,121,219,.08);transition:transform .16s ease,box-shadow .16s ease}.document-link:active{transform:scale(.98);box-shadow:none}.document-link-icon{width:38px;height:38px;flex:0 0 38px;border-radius:11px;background:#fff;display:grid;place-items:center;color:var(--blue);box-shadow:0 5px 14px rgba(8,121,219,.12)}.document-link-icon svg{width:20px;height:20px}.document-link-copy{min-width:0;flex:1}.document-link-copy small{display:block;margin-top:2px;color:#718096;font-size:9px;font-weight:650}.document-link-arrow{font-size:20px;line-height:1}
    .status-card{position:relative;min-height:102px;display:flex;align-items:center;gap:14px;padding:17px;border-radius:15px;background:linear-gradient(135deg,var(--status-soft),#fff);border:1px solid color-mix(in srgb,var(--status) 13%,var(--line));overflow:hidden;animation:rise .48s .05s ease both}.status-card:after{content:"";position:absolute;width:120px;height:120px;border-radius:50%;right:-72px;top:-72px;background:color-mix(in srgb,var(--status) 8%,transparent)}.status-icon{position:relative;z-index:1;width:58px;height:58px;flex:0 0 58px;border-radius:50%;display:grid;place-items:center;background:color-mix(in srgb,var(--status) 13%,#fff);font-size:29px;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--status) 12%,transparent),0 8px 18px color-mix(in srgb,var(--status) 10%,transparent);animation:status-float 2.8s ease-in-out infinite}.status-copy{position:relative;z-index:1;min-width:0;flex:1}.status-title{color:var(--status);font-size:19px;line-height:1.15;font-weight:950;letter-spacing:-.35px;margin:0 0 5px}.status-description{color:#4d596c;font-size:11px;line-height:1.45;margin:0}
    .tracker{position:relative;display:grid;grid-template-columns:repeat(6,minmax(0,1fr));margin:13px 0 17px;padding-top:1px}.track-rail{position:absolute;z-index:0;left:8.333%;right:8.333%;top:15px;height:2px;border-radius:2px;background:#dfe5ec;overflow:hidden}.track-progress{height:100%;width:0;border-radius:2px;background:linear-gradient(90deg,#0789e4,var(--status));transition:width 1.05s cubic-bezier(.2,.75,.25,1)}.track-step{position:relative;z-index:1;min-width:0;text-align:center;opacity:0;transform:translateY(7px);animation:step-in .35s ease forwards;animation-delay:calc(var(--i) * 65ms + 140ms)}.track-dot{width:28px;height:28px;margin:0 auto;border-radius:50%;background:#edf1f5;border:2px solid #edf1f5;color:#7b8798;display:grid;place-items:center;font-size:11px;font-weight:950;transition:.35s ease}.track-label{display:block;margin-top:6px;color:#778397;font-size:8px;line-height:1.15;font-weight:750;white-space:nowrap}.track-step.reached .track-dot{background:#0789e4;border-color:#0789e4;color:#fff}.track-step.current .track-dot{background:var(--status);border-color:var(--status);box-shadow:0 0 0 0 color-mix(in srgb,var(--status) 35%,transparent);animation:current-pulse 1.9s infinite}.track-step.current .track-label{color:var(--status);font-weight:950}
    .recent{margin-top:2px}.recent-heading{font-size:13px;font-weight:900;margin:0 0 9px}.event{position:relative;min-height:74px;padding:11px 12px 11px 16px;border-left:2px solid var(--status);background:linear-gradient(90deg,var(--status-soft),rgba(255,255,255,.35));border-radius:0 12px 12px 0;animation:event-in .48s .28s ease both}.event-date{display:block;color:#8d9aab;font-size:9px;font-weight:650;margin-bottom:3px}.event-title{display:block;color:var(--status);font-size:12px;font-weight:900;margin-bottom:2px}.event-description{color:#657287;font-size:10px;line-height:1.35;margin:0}
    .privacy{display:flex;align-items:center;justify-content:center;gap:5px;margin:15px 0 0;color:#8a96a7;font-size:9px}.privacy svg{width:12px;height:12px}
    .actions{position:fixed;z-index:30;left:50%;bottom:calc(8px + env(safe-area-inset-bottom));transform:translateX(-50%);width:min(calc(100% - 20px),456px);min-height:62px;display:grid;grid-template-columns:1fr 1.2fr 1fr;gap:7px;padding:6px;background:rgba(255,255,255,.94);backdrop-filter:blur(16px);border:1px solid var(--line);border-radius:16px;box-shadow:0 16px 44px rgba(25,48,80,.18)}.action{min-width:0;min-height:48px;border-radius:11px;background:#fff;color:#0873d4;border:1px solid #dce5f0;text-decoration:none;display:flex;align-items:center;justify-content:center;gap:5px;font-size:10px;font-weight:850;cursor:pointer;transition:transform .15s ease,background .15s ease}.action svg{width:16px;height:16px;flex:0 0 16px}.action-wa{color:#119c4b}.action-refresh{color:#0873d4}.action:active{transform:scale(.96);background:#f4f8fc}.action:disabled{opacity:.55}.action-refresh.loading svg{animation:spin .75s linear infinite}.actions.no-phone{grid-template-columns:1fr}
    .state{margin-top:20px;padding:42px 22px;text-align:center}.state-icon{width:66px;height:66px;border-radius:22px;background:var(--blue-soft);color:var(--blue);display:grid;place-items:center;margin:0 auto 15px}.state h1{font-size:19px;margin:0 0 7px}.state p{color:var(--muted);font-size:12px;line-height:1.5;margin:0}.spinner{width:27px;height:27px;border:3px solid #cfe0ef;border-top-color:var(--blue);border-radius:50%;animation:spin .8s linear infinite}.retry{width:100%;min-height:48px;margin-top:17px;border-radius:12px;background:var(--blue-soft);color:var(--blue);font-weight:850;cursor:pointer}
    .hidden{display:none!important}
    @keyframes spin{to{transform:rotate(360deg)}}@keyframes live-pulse{70%{box-shadow:0 0 0 8px transparent}}@keyframes current-pulse{70%{box-shadow:0 0 0 9px transparent}}@keyframes status-float{50%{transform:translateY(-3px) rotate(-2deg)}}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@keyframes step-in{to{opacity:1;transform:none}}@keyframes event-in{from{opacity:0;transform:translateX(-8px)}to{opacity:1;transform:none}}
    @media(min-width:600px){.page{min-height:auto;margin:24px auto;background:#fff;border:1px solid var(--line);border-radius:28px;box-shadow:0 24px 70px rgba(25,48,80,.12)}body{padding-bottom:24px}}
    @media(max-width:350px){.page{padding-left:8px;padding-right:8px}.sheet-card{padding:13px}.status-card{padding:14px;gap:10px}.status-icon{width:50px;height:50px;flex-basis:50px;font-size:24px}.status-title{font-size:17px}.track-label{font-size:7px}.actions{width:calc(100% - 12px);gap:4px}.action{font-size:9px}}
    @media(prefers-reduced-motion:reduce){*{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
  </style>
</head>
<body>
  <main class="page">
    <header class="header">
      <div class="brand"><img class="brand-logo" src="./assets/logo.png" alt="G-Shop"><div class="brand-copy"><span class="brand-title">G-Shop</span><span class="brand-property" id="propertyName">Urmărire reparație</span></div></div>
      <h1 class="tracking-title">Urmărește statusul reparației</h1>
      <div class="live"><span class="live-dot"></span><span>Informațiile sunt actualizate în timp real</span></div>
    </header>

    <section id="loading" class="card state"><div class="state-icon"><div class="spinner"></div></div><h1>Se încarcă statusul</h1><p>Preluăm cele mai noi informații direct din service.</p></section>
    <section id="error" class="card state hidden"><div class="state-icon">!</div><h1>Link indisponibil</h1><p id="errorText">Statusul nu a putut fi încărcat.</p><button class="retry" id="errorRetry" type="button">Încearcă din nou</button></section>

    <div id="content" class="hidden">
      <section class="card sheet-card">
        <span class="sheet-label">Fișă service</span><strong class="sheet-number" id="sheetNumber">În curs de creare</strong>
        <p class="equipment" id="equipment">Echipament înregistrat</p>
        <div class="sheet-meta"><div class="meta"><span class="meta-label">Primit în data de</span><strong class="meta-value" id="receivedAt">—</strong></div><div class="meta"><span class="meta-label">Ultima actualizare</span><strong class="meta-value" id="updatedAt">—</strong></div></div>
      </section>
      <a id="serviceSheetButton" class="document-link hidden" target="_blank" rel="noopener"><span class="document-link-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/></svg></span><span class="document-link-copy">Vezi fișa de service<small>Se deschide PDF-ul actualizat într-un tab nou</small></span><span class="document-link-arrow">›</span></a>

      <section class="status-card" id="statusCard"><div class="status-icon" id="statusIcon">●</div><div class="status-copy"><h2 class="status-title" id="statusLabel">Client înregistrat</h2><p class="status-description" id="statusDescription"></p></div></section>

      <section id="repairProgress">
        <div class="tracker" id="tracker"><div class="track-rail"><div class="track-progress" id="trackProgress"></div></div>
          <div class="track-step" data-index="0" style="--i:0"><div class="track-dot">1</div><span class="track-label">Preluare</span></div>
          <div class="track-step" data-index="1" style="--i:1"><div class="track-dot">2</div><span class="track-label">Verificare</span></div>
          <div class="track-step" data-index="2" style="--i:2"><div class="track-dot">3</div><span class="track-label">Lucru</span></div>
          <div class="track-step" data-index="3" style="--i:3"><div class="track-dot">4</div><span class="track-label">Piese</span></div>
          <div class="track-step" data-index="4" style="--i:4"><div class="track-dot">5</div><span class="track-label">Finalizare</span></div>
          <div class="track-step" data-index="5" style="--i:5"><div class="track-dot">6</div><span class="track-label">Predare</span></div>
        </div>
      </section>

      <section class="recent"><h2 class="recent-heading">Actualizări recente</h2><div class="event"><span class="event-date" id="eventDate">—</span><strong class="event-title" id="eventTitle">Fișa a fost creată</strong><p class="event-description" id="eventDescription"></p></div></section>
      <div class="privacy"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="5" y="10" width="14" height="10" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><span>Link privat, destinat exclusiv clientului</span></div>
    </div>
  </main>

  <nav class="actions hidden" id="actions" aria-label="Acțiuni rapide"><a id="callButton" class="action"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.9v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 3.1 5.2 2 2 0 0 1 5.1 3h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L9.1 10.9a16 16 0 0 0 4 4l1.2-1.2a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/></svg>Sună</a><a id="whatsappButton" class="action action-wa" target="_blank" rel="noopener" aria-label="Deschide conversația WhatsApp"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479s1.065 2.875 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.262.489 1.693.625.712.227 1.36.195 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.29.173-1.414-.074-.123-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884a9.82 9.82 0 0 1 6.988 2.895 9.825 9.825 0 0 1 2.89 6.99c-.002 5.45-4.437 9.884-9.889 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.82 11.82 0 0 0-3.48-8.413Z"/></svg>WhatsApp</a><button id="refresh" class="action action-refresh" type="button"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 11a8 8 0 1 0-2.3 5.7L20 14"/><path d="M20 5v6h-6"/></svg><span>Reîncarcă</span></button></nav>

  <script>
    const token=<?php echo json_encode($token, JSON_UNESCAPED_SLASHES); ?>;
    const endpoint='./index.php/public/client-form/'+encodeURIComponent(token);
    const STATUS={
      NEW:{label:'Nouă',description:'Dispozitivul a fost înregistrat în sistem.',event:'Fișa de service a fost creată',icon:'📄',color:'#0879db',soft:'#eaf5ff'},
      WAITING:{label:'În așteptare',description:'Dispozitivul așteaptă să fie preluat în service.',event:'Așteaptă preluarea',icon:'⌛',color:'#f09a00',soft:'#fff5e3'},
      VERIFYING:{label:'În verificare',description:'Tehnicianul verifică dispozitivul și identifică problema.',event:'Diagnosticare în desfășurare',icon:'🔍',color:'#7651ad',soft:'#f4effc'},
      IN_PROGRESS:{label:'În lucru',description:'Tehnicianul lucrează în acest moment la dispozitiv.',event:'Reparația a început',icon:'🛠',color:'#0879db',soft:'#eaf5ff'},
      WAITING_PARTS:{label:'Se așteaptă piesele',description:'Piesele necesare au fost comandate.',event:'Piese comandate',icon:'📦',color:'#ef6900',soft:'#fff2e8'},
      COMPLETED:{label:'Finalizată',description:'Dispozitivul este pregătit pentru predare.',event:'Reparația este finalizată',icon:'✓',color:'#15913e',soft:'#edf8ef'},
      DELIVERED:{label:'Predată',description:'Dispozitivul a fost predat clientului.',event:'Dispozitiv predat',icon:'👥',color:'#0b7332',soft:'#edf7f0'},
      CANCELLED:{label:'Anulată',description:'Lucrarea a fost anulată. Contactează unitatea service.',event:'Lucrare anulată',icon:'×',color:'#e43b50',soft:'#fff0f2'}
    };
    const STEP={NEW:0,WAITING:0,VERIFYING:1,IN_PROGRESS:2,WAITING_PARTS:3,COMPLETED:4,DELIVERED:5,CANCELLED:-1};
    const $=id=>document.getElementById(id);const show=id=>$(id).classList.remove('hidden');const hide=id=>$(id).classList.add('hidden');const setText=(id,value)=>{$(id).textContent=value??''};
    const formatDate=(value,withTime=false)=>{if(!value)return '—';const date=new Date(value);if(Number.isNaN(date.getTime()))return '—';const options=withTime?{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'long',year:'numeric'};return new Intl.DateTimeFormat('ro-RO',options).format(date)};
    const whatsappPhone=value=>{let digits=String(value||'').replace(/\D/g,'');if(digits.startsWith('00'))digits=digits.slice(2);if(digits.startsWith('0'))digits='40'+digits.slice(1);return digits};

    function renderProgress(status){const current=STEP[status]??0;const steps=[...document.querySelectorAll('.track-step')];steps.forEach((step,index)=>{step.classList.toggle('reached',current>=0&&index<=current);step.classList.toggle('current',index===current);step.querySelector('.track-dot').textContent=current>=0&&index<=current?'✓':String(index+1)});$('tracker').style.setProperty('--status',STATUS[status]?.color||'#0879db');requestAnimationFrame(()=>{$('trackProgress').style.width=current<0?'0%':(current/(steps.length-1)*100)+'%'})}
    function renderContact(data){const phone=String(data.contact?.phone||'').trim();if(phone){const tel=phone.replace(/[^\d+]/g,'');$('callButton').href='tel:'+tel;const wa=whatsappPhone(phone);$('whatsappButton').href='https://wa.me/'+wa+'?text='+encodeURIComponent('Bună ziua! Vă contactez în legătură cu statusul reparației mele.')}else{$('callButton').classList.add('hidden');$('whatsappButton').classList.add('hidden');$('actions').classList.add('no-phone')}show('actions')}
    function render(data){const repair=data.repair;const current=repair?STATUS[repair.status]:STATUS.NEW;document.documentElement.style.setProperty('--status',current.color);document.documentElement.style.setProperty('--status-soft',current.soft);setText('propertyName',data.propertyName||'Urmărire reparație');document.title='Status reparație · '+(data.propertyName||'G-Shop');setText('sheetNumber',repair?.number||'În curs de creare');setText('equipment',repair?[repair.brand,repair.model,repair.equipment].filter(Boolean).join(' · ')||'Echipament înregistrat':'Fișa de service se pregătește');setText('receivedAt',formatDate(repair?.receivedAt));setText('updatedAt',formatDate(repair?.updatedAt||data.client.updatedAt,true));setText('statusIcon',current.icon);setText('statusLabel',current.label);setText('statusDescription',current.description);setText('eventDate',formatDate(repair?.updatedAt||data.client.updatedAt,true));setText('eventTitle',current.event);setText('eventDescription',current.description);if(repair?.serviceSheetUrl){$('serviceSheetButton').href=repair.serviceSheetUrl;show('serviceSheetButton')}else hide('serviceSheetButton');renderProgress(repair?.status||'NEW');renderContact(data)}
    async function load(){hide('error');const firstLoad=$('content').classList.contains('hidden');if(firstLoad)show('loading');const button=$('refresh');button.disabled=true;button.classList.add('loading');button.querySelector('span').textContent='Se încarcă';try{const response=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'Statusul nu a putut fi încărcat.');render(payload.data);hide('loading');hide('error');show('content')}catch(error){hide('loading');if(firstLoad){hide('content');hide('actions');show('error');setText('errorText',error.message||'Statusul nu a putut fi încărcat.')}}finally{button.disabled=false;button.classList.remove('loading');button.querySelector('span').textContent='Reîncarcă'}}
    $('refresh').addEventListener('click',load);$('errorRetry').addEventListener('click',load);load();
  </script>
</body>
</html>
